### ISSUE TITLE
Download and Install link doesn't take to the right section on the page.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-core-components.en#20] opened 2020-08-13 14:57 UTC
Issue in ./help/get-started/using.md

* Download and Install link doesn't take to the correct section on the page. Incorrect:
![image](https://user-images.githubusercontent.com/59624839/90150135-55385280-dd53-11ea-9915-087c9d897850.png)

* Download and Install link on the right panel (below ON THIS PAGE) takes to the correct section on the page. Correct:
![image](https://user-images.githubusercontent.com/59624839/90150493-b8c28000-dd53-11ea-843f-989937045890.png)

[Logged by AEM Support]

**Comment by bohnertchris** [comment] 2021-02-11 07:57
Thanks for reporting this, @sukohli, and apologies for how long it took to respond. It appears that something has gone wrong with our alert filters on this repo. We will look into it.

Regarding the issue, I think this was a problem with the markdown platform that has since been addressed by SCCM engineering as I am unable to reproduce it.

**Closed as completed by bohnertchris** 2021-02-11 07:57 UTC
Labels: Bug
